import dynamic from 'next/dynamic'
const Plum = dynamic(() => import('@/components/Plum'), {
  ssr: false,
})
import Header from '../components/Header'
import Main from '../components/Main'
import Footer from '../components/Footer'
import './globals.css'
import type { Metadata } from 'next'
import ThemeProvider from '../components/Header/components//Theme/provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <div id="__next">
            <div id="app" className="h-100% flex flex-col">
              <Header />
              <Main>{children}</Main>
              <Footer />
            </div>
            <Plum />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
