import dynamic from 'next/dynamic'
const Plum = dynamic(() => import('@/components/Plum'), {
  ssr: false,
})
import Header from '@/components/layout/Header'
import Main from '@/components/layout/Main'
import Footer from '@/components/layout/Footer'
import './globals.css'
import type { Metadata } from 'next'
import ThemeProvider from '@/components/layout/Header/components//Theme/provider'
import Resize from './resize'

export const metadata: Metadata = {
  title: "Rain's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Resize>
          <ThemeProvider>
            <div id="__next" className="h-full relative flex flex-col">
              <Header />
              <Main>{children}</Main>
              <Footer />
            </div>
            <Plum />
          </ThemeProvider>
        </Resize>
      </body>
    </html>
  )
}
